### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by mgottschlag**
Hi,

I've ported the code to newer linux/dpdk versions as that makes it much easier to use fastpass on current systems. These changes seem to allow fastpass to run on Linux 4.1 and DPDK 16.07. They do break the code with older versions though.

There are 1-2 unrelated fixes which seemed to be required to successfully run fastpass. I have not done any extensive testing yet to see whether they break anything.

I don't know whether these changes should be incorporated as-is, but it might make sense to prevent diverging github repositories and the resulting confusion.

Greetings,
Mathias

### CODE REVIEW

**Comment by yonch** [comment]
The code looks good. Thank you Mathias for contributing your changes!

Regarding testing, did you verify that endpoints can still connect to the arbiter? The hash change might break that, so good to verify. Will merge if you're confident it works.

Jonathan

**Comment by mgottschlag** [comment]
As I understood it, endpoints could connect even when the hashes differed... at least that is how it looked to me. I can send packets between two endpoints which both use fastpass, but I could do that even before the hash change.

I would have expected that the scheduler would not have recognized collisions (hopefully, it does now), because the same system was known by two different IDs (one for outgoing, one for incoming packets, depending on where the hash was calculated).

https://patchwork.kernel.org/patch/6493051/ <- this is the linux kernel change for the hash algorithm

**Comment by yonch** [comment]
Thanks for sending Mathias.

In arbiter->endpoint and endpoint->arbiter communication, each end verifies the hashes on incoming packets, similar to what CRC is used in the TCP checksum.

If the hash implementation differs between the endpoint (in the kernel) and the arbiter (in dpdk, userspace), then the arbiter and endpoints would not be able to communicate -- each side would drop the other's packets before fully processing them.

Do you know if the hashes are compatible after applying your pull request?

Jonathan

**Comment by mgottschlag** [comment]
Ah, yes, of course, that check should work now.

I had that commented that check out temporarily, but it is working again after the hash change.

**Comment by yonch** [comment]
Thank you Mathias for contributing. Merged!

**Pull request merged**
